"""Add structured locations

Revision ID: d23da7ae8bc7
Revises: 
Create Date: 2025-06-07 15:12:30.684796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23da7ae8bc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('template_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_unit_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['label_type_id'], ['label_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(length=10), nullable=False),
    sa.Column('column_label', sa.String(length=10), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['storage_unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_units')
    op.drop_table('storage_unit_types')
    op.drop_table('levels')
    op.drop_table('modules')
    op.drop_table('label_types')
    # ### end Alembic commands ###
